"""schema inicial: hierarquia e leituras

Revision ID: 518f06b50068
Revises: 
Create Date: 2026-09-04 15:14:56.124677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '518f06b50068'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots_defeito',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leitura_id', sa.Uuid(), nullable=False),
    sa.Column('leitura_tipo', sa.String(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('tipo_defeito', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planta_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maquinas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maquina_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ultima_leitura_persistida_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['ultima_leitura_persistida_id'], ['leituras_persistidas.id'], name='fk_ponto_ultima_leitura', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leituras_persistidas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ponto_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_original', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotacao', sa.Float(), nullable=False),
    sa.Column('picos_r3', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rms_total', sa.Float(), nullable=False),
    sa.Column('rms_ruido', sa.Float(), nullable=False),
    sa.Column('rms_picos', sa.Float(), nullable=False),
    sa.Column('valor_dc', sa.Float(), nullable=False),
    sa.Column('nivel_alerta', sa.Float(), nullable=True),
    sa.Column('nivel_shutdown', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leituras_trash',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ponto_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_original', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotacao', sa.Float(), nullable=False),
    sa.Column('picos_r3', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rms_total', sa.Float(), nullable=False),
    sa.Column('rms_ruido', sa.Float(), nullable=False),
    sa.Column('rms_picos', sa.Float(), nullable=False),
    sa.Column('valor_dc', sa.Float(), nullable=False),
    sa.Column('motivo_descarte', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leituras_trash')
    op.drop_table('leituras_persistidas')
    op.drop_table('pontos')
    op.drop_table('maquinas')
    op.drop_table('areas')
    op.drop_table('snapshots_defeito')
    op.drop_table('plantas')
    # ### end Alembic commands ###
